// Spofity
export const SPOTIFY_SET_ACCESS_TOKEN = 'SPOTIFY_SET_ACCESS_TOKEN';
export const SPOTIFY_SET_TOKEN_TYPE = 'SPOTIFY_SET_TOKEN_TYPE';
export const SPOTIFY_SET_EXPIRESIN = 'SPOTIFY_SET_EXPIRESIN';
export const SPOTIFY_FETCH_PROFIL_DATA = 'SPOTIFY_FETCH_PROFIL_DATA';
export const SPOTIFY_FETCH_PLAYLIST_DATA = 'SPOTIFY_FETCH_PLAYLIST_DATA';
// Deezer
export const DEEZER_SET_ACCESS_TOKEN = 'DEEZER_SET_ACCESS_TOKEN';
export const DEEZER_SET_TOKEN_TYPE = 'DEEZER_SET_TOKEN_TYPE';
export const DEEZER_SET_EXPIRESIN = 'DEEZER_SET_EXPIRESIN';
export const DEEZER_FETCH_PROFIL_DATA = 'DEEZER_FETCH_PROFIL_DATA';
export const DEEZER_FETCH_PLAYLIST_DATA = 'DEEZER_FETCH_PLAYLIST_DATA';
